id: P000610
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:51:08.865455
source_metadata:
  id: bdr:W1KG8464
  title: བླ་མའི་རྣལ་འབྱོར་བྱིན་རླབས་མྱུར་སྩོལ་གྱི་ཁྲིད་ཡིག
  author: ''
  volumes:
    85ed0c27235c47559d2b3b1c7ffcc3a7:
      image_group_id: I1KG8503
      title: ''
      volume_number: 1
      total_pages: 104
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
